close all;
tmin=0;
tmax=10^-3;
step=(tmax-tmin)/1000;
t=tmin:step:tmax;
Am=1;
fm=2*10^3;
m1=Am*sin(2*pi*fm*t+0);
figure(1);
subplot(4,1,1);
plot(t,m1);
xlabel('time');
ylabel('amplitude');
title('message signal');
grid on;
tmin=0;
tmax=10^-3;
step=(tmax-tmin)/1000;
t=tmin:step:tmax;
Ac=1;
fc=10^4;
c1=Ac*sin(2*pi*fc*t+0);
subplot(4,1,2);
plot(t,c1);
xlabel('time');
ylabel('amplitude');
title('carrier signal');
grid on;
%figure(2);
m2=Am*sin(2*pi*fm*t+90);
c2=Ac*sin(2*pi*fc*t+90);
subplot(4,1,3);
plot(t,m2);
xlabel('time');
ylabel('amplitude');
title('message signal with 90 degree phase shift');
grid on;
subplot(4,1,4);
plot(t,c2);
xlabel('time');
ylabel('amplitude');
title('carrier signal with 90 degree phase shift');
grid on;
s=m1.*c2+m2.*c1;
figure(2);
plot(t,s);
xlabel('time');
ylabel('amplitude');
title('SSB-SC signal');
grid on;